---
- name: Test connection for Ubuntu machines
  hosts: control_plane
  become: true
  vars_files:
    - variables.yml

  tasks:
    - name: Test Connection
      ping:

- name: Test connection for Windows Server machines
  hosts: workers_win
  vars_files:
    - variables.yml

  tasks:    
    - name: Test Connection
      win_ping:
