---
- hosts: control_plane
  become: true
  vars_files:
    - variables.yml

  tasks:
    - name: Test Connection
      ping:
---
- hosts: workers_win
  become: true
  vars_files:
    - variables.yml

  tasks:
    - name: Test Connection
      win_ping: