---
- name: Install Kubernetes in Ubuntu
  hosts: all
  become: true
  vars_files:
    - variables.yml

  tasks:
    - name: Disable swap
      command: swapoff -a
    
    - name: Disable swap in /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^(.+?\s+swap\s+sw\s+.+?)$'
        replace: '#\1'
    
    - name: Modify the nameserver in resolv.conf
      replace:
        path: /etc/resolv.conf
        regexp: '^(.+?\s+nameserver\s+.+?)$'
        replace: 'nameserver 8.8.8.8 8.8.4.4'
    
    - name: Create iptables rule file for K8s
      file:
        path: /etc/sysctl.d/k8s.conf
        state: touch
        mode: 0644

    - name: Empty file content /etc/sysctl.d/k8s.conf
      copy:
        content: ""
        dest: /etc/sysctl.d/k8s.conf

    - name: Ensure iptables tooling does not use the nftables backend
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        state: present
        create: yes
        line: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
    
    - name: Apply sysctl params
      command: sysctl --system

    - name: Make sure that br_netfilter module is loaded
      modprobe:
        name: br_netfilter

    - name: Add br_netfilter module to /etc/modules-load.d/modules.conf
      lineinfile:
        path: /etc/modules-load.d/modules.conf
        state: present
        create: yes
        line: br_netfilter

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Add Kubernetes apt-key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes apt repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    - name: Install Kubernetes packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        allow_downgrades: true
      loop: "{{ kubernetes_engines }}"

    - name: Hold Kubernetes packages version
      command: apt-mark hold kubelet kubeadm kubectl

      